name: get_flutter_fire
version: 1.0.0+1
publish_to: none
description: Boilerplate for Flutter with GetX, showing sample utilization of Firebase capabilities
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.14.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2
  google_fonts: ^6.2.1
  firebase_storage: ^12.3.2
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  path: ^1.9.0
  get_storage: ^2.1.1
  firebase_ui_localizations: ^1.12.0
  firebase_remote_config: ^5.1.3
  firebase_analytics: ^11.3.3
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.1.6
  cloud_firestore: ^5.4.3
  firebase_app_check: ^0.3.1+3

  # Add other Firebase dependencies as needed

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  assets:
    - assets/images/
    - assets/images/dash.png
    - assets/icons/logo.png

flutter_native_splash:
  image: assets/images/splash.png
  color: "#000000"
